In [1]:
import pandas as pd;
excel_file_address = "http://saffarizadeh.com/ET/Students.xlsx";

In [2]:
students_sheet1 = pd.read_excel(excel_file_address, sheet_name=0, index_col=0)

In [6]:
students_sheet1.head(3)

   First Name Last Name  Quiz 1  Quiz 2  Attendance
ID
1      Amalia   Pearson      90      80           5
2      Leyton  Richmond     100      80           4
3     Phoenix   Stanton      85     100           3

In [9]:
students_sheet2 = pd.read_excel(excel_file_address, sheet_name=1)

In [10]:
students_sheet2

   Number of Sessions  Quiz Weight  Attendance Weight
0                   5          0.7                0.3

In [11]:
students_sheet3 = pd.read_excel(excel_file_address, sheet_name=2, index_col=0)

In [12]:
students_sheet3.head()

      Email
ID
1   a@b.com
2   b@c.com
3       NaN
4       NaN
5       NaN

# Analyzing and modifying an Excel file.

In [13]:
students_sheet1.describe()

           Quiz 1    Quiz 2  Attendance
count    5.000000    5.0000     5.00000
mean    89.000000   88.0000     4.20000
std      7.416198    8.3666     0.83666
min     80.000000   80.0000     3.00000
25%     85.000000   80.0000     4.00000
50%     90.000000   90.0000     4.00000
75%     90.000000   90.0000     5.00000
max    100.000000  100.0000     5.00000

## Access rows and columns

In [14]:
students_sheet1[0:2]

   First Name Last Name  Quiz 1  Quiz 2  Attendance
ID
1      Amalia   Pearson      90      80           5
2      Leyton  Richmond     100      80           4

In [15]:
students_sheet1.loc[1]

First Name     Amalia
Last Name     Pearson
Quiz 1             90
Quiz 2             80
Attendance          5
Name: 1, dtype: object

In [16]:
students_sheet1.iloc[0]

First Name     Amalia
Last Name     Pearson
Quiz 1             90
Quiz 2             80
Attendance          5
Name: 1, dtype: object

In [18]:
students_sheet1.iloc[0:2]

   First Name Last Name  Quiz 1  Quiz 2  Attendance
ID
1      Amalia   Pearson      90      80           5
2      Leyton  Richmond     100      80           4

In [20]:
students_sheet1['Quiz 1']

ID
1     90
2    100
3     85
4     90
5     80
Name: Quiz 1, dtype: int64

In [22]:
students_sheet1[['Quiz 1', 'Quiz 2']]

    Quiz 1  Quiz 2
ID
1       90      80
2      100      80
3       85     100
4       90      90
5       80      90

In [27]:
students_sheet1['Quiz 1'][1]

90

In [28]:
students_sheet1.at[1, 'Quiz 1']

90

In [30]:
students_sheet1.iat[0, 2]

90

In [32]:
students_sheet1[["Last Name", "Quiz 2"]]

   Last Name  Quiz 2
ID
1    Pearson      80
2   Richmond      80
3    Stanton     100
4     Cotton      90
5      Perez      90

## Analyze the data

In [50]:
results = students_sheet1[students_sheet1['Quiz 1'] >= 85]

In [51]:
results

   First Name Last Name  Quiz 1  Quiz 2  Attendance
ID
1      Amalia   Pearson      90      80           5
2      Leyton  Richmond     100      80           4
3     Phoenix   Stanton      85     100           3
4      Hafsah    Cotton      90      90           4

In [59]:
results[['First Name', 'Last Name']];

In [54]:
students_sheet1[students_sheet1['Quiz 1'] >= 85]

   First Name Last Name  Quiz 1  Quiz 2  Attendance
ID
1      Amalia   Pearson      90      80           5
2      Leyton  Richmond     100      80           4
3     Phoenix   Stanton      85     100           3
4      Hafsah    Cotton      90      90           4

In [56]:
students_sheet1['Quiz 1'].mean()

89.0

In [58]:
students_sheet1[students_sheet1['Quiz 1'] >= students_sheet1['Quiz 1'].mean()]

   First Name Last Name  Quiz 1  Quiz 2  Attendance
ID
1      Amalia   Pearson      90      80           5
2      Leyton  Richmond     100      80           4
4      Hafsah    Cotton      90      90           4

Python: and, or

C# & Java: &&, ||

Pandas: &, |

In [68]:
students_sheet1[ (students_sheet1['Quiz 1'] >=85) & (students_sheet1["Quiz 2"] >= 90) ]

   First Name Last Name  Quiz 1  Quiz 2  Attendance
ID
3     Phoenix   Stanton      85     100           3
4      Hafsah    Cotton      90      90           4

In [71]:
students_sheet2

   Number of Sessions  Quiz Weight  Attendance Weight
0                   5          0.7                0.3

In [70]:
students_sheet2["Number of Sessions"].to_numpy()

array([5])

In [73]:
students_sheet1["Attendance Score"] = 100 * students_sheet1["Attendance"] / students_sheet2["Number of Sessions"].to_numpy()

In [74]:
students_sheet1

   First Name Last Name  Quiz 1  Quiz 2  Attendance  Attendance Score
ID
1      Amalia   Pearson      90      80           5             100.0
2      Leyton  Richmond     100      80           4              80.0
3     Phoenix   Stanton      85     100           3              60.0
4      Hafsah    Cotton      90      90           4              80.0
5        Cloe     Perez      80      90           5             100.0